version: '3.7'

services:
  db:
    container_name: postgres-email
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data/

  api:
    container_name: email-api
    build: ./api
    env_file:
      - ./.env
    volumes:
      - ./api:/api
      - /api/venv
    ports:
      - 8000:8000
    command: [ "/api/api.sh" ]
    depends_on:
      - db
      - redis

  client:
    build: ./frontend
    ports:
      - "80:80"
    container_name: email-client
    volumes:
      - ./frontend:/client
    depends_on:
      - api

  redis:
    image: redis:7
    container_name: email-redis

  celery:
    build: ./api
    env_file:
      - ./.env
    container_name: email-celery
    command: [ "/api/celery.sh", "celery" ]
    volumes:
      - ./api:/api
      - /api/venv
    depends_on:
      - redis
      - api

  flower:
    build: ./api
    env_file:
      - ./.env
    container_name: email-flower
    command: [ "/api/celery.sh", "flower" ]
    depends_on:
      - redis
      - celery
      - api
    ports:
      - 5555:5555
