version: '3.7'

services:
  db:
    container_name: postgres-email
    image: postgres:12
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data/

  api:
    container_name: email-api
    build: ./api
    env_file:
      - ./.env
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - db

  client:
    build: ./frontend
    ports:
      - "80:80"
    container_name: email-client
    depends_on:
      - api
